Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,33 +1,84 @@
-name: Run Unit Test via Pytest
+name: Selenium Tests
 
-on: [push]
+on:
+  workflow_dispatch:  # Allows running manually
+  schedule:
+    - cron: '0 0 * * *'  # Run every day at 00:00 UTC
 
 jobs:
-  build:
-    runs-on: ubuntu-latest
-    strategy:
-      matrix:
-        python-version: ["3.10"]
+  selenium-tests:
+    runs-on: macos-latest
+    env:
+      DEV_URL: ${{ vars.DEV_URL }}
+      STAG_URL: ${{ vars.STAG_URL }}
+
+    permissions:
+      checks: write
 
     steps:
-      - uses: actions/checkout@v3
-      - name: Set up Python ${{ matrix.python-version }}
-        uses: actions/setup-python@v4
+      - name: Checkout repository
+        uses: actions/checkout@v3
+
+      - name: Setup Python
+        uses: actions/setup-python@v3
         with:
-          python-version: ${{ matrix.python-version }}
-      - name: Install dependencies
+          python-version: "3.12"
+
+      - name: Cache Dependencies
+        uses: actions/cache@v3
+        with:
+          path: |
+            ~/.cache/pip
+            .venv
+          key: python-cache-${{ runner.os }}-${{ hashFiles('poetry.lock') }}
+          restore-keys: |
+            python-cache-${{ runner.os }}-
+
+      - name: Install Chrome and WebDriver if not already installed
+        run: |
+          if ! command -v google-chrome &>/dev/null; then
+            echo "Installing Chrome"
+            brew install --cask google-chrome
+          else
+            echo "Chrome is already installed"
+          fi
+
+      - name: Install Poetry
         run: |
           python -m pip install --upgrade pip
-          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
-      - name: Lint with Ruff
+          pip install poetry
+
+      - name: Install dependencies with Poetry
         run: |
-          pip install ruff
-          ruff --format=github --target-version=py310 .
-        continue-on-error: true
-      - name: Test with pytest
+          poetry install
+
+      - name: Run Selenium Tests
         run: |
-          coverage run -m pytest  -v -s
-      - name: Generate Coverage Report
-        run: |
-          coverage report -m
+          poetry run pytest --verbose --junit-xml=reports/test-results.xml --capture=tee-sys
+        continue-on-error: true  # Ensure other steps run even if tests fail
+
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v3
+        if: always()  # Always run this step, even if tests fail
+        with:
+          report_paths: 'reports/test-results.xml'
+          detailed_summary: true
+          include_passed: true
+          check_name: 'Test Results'
+          follow_symlink: True
+
+      - name: Upload Screenshots
+        if: failure()
+        uses: actions/upload-artifact@v3
+        with:
+          name: screenshots
+          path: reports/screenshots/*
+
+      - name: Upload Test Results
+        if: always()
+        uses: actions/upload-artifact@v3
+        with:
+          name: junit-test-results
+          path: reports/test-results.xml
+          retention-days: 1
           
